# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += Employee_Access/Employee_Access.pro \
    UserDatDLL/UserDatDLL.pro

LIBS += -L C:/Users/Administrator/Documents/Visual Studio 2015/Projects/Employee_Access/x64/Debug -I UserDatDLL
